### ISSUE TITLE
Stop using `calicoctl` for profile configuration

### ISSUE THREAD

**Issue by alexhersh** [projectcalico/calico-kubernetes#11]
Currently, semantic rules can only be added by `calicoctl` one at a time. Ideally we want to support profile _updating_ as opposed to _appending_ with this format. We also do not want this plugin to call `calicoctl` at all, but some work needs to be done to allow the pycalico datastore to accept our semantic format. 

A symptom of this is that we need to flush out the default rules before adding in new policy. This is currently done naively with `calicoctl` calls that target rules that are assumed to exist. If these defaults change, new policy will be disrupted. Default rule replacement should be more dynamic (and preferably without `calicoctl` calls)

**Comment by caseydavenport** [comment]
Changing to low priority, since ideally this will just go away once we can get proper policy support in the Kubernetes API (either native, pluggable, etc) and we no longer need to use the calicoctl styled policy statements in annotations.

It would be nice to remove the calicoctl dependency once and for all, but I don't think we should move the argparsing stuff into libcalico, especially if its just for this use case.

**Comment by caseydavenport** [comment]
The last remaining calls to `calicoctl`are applying advanced policy rules.  To remove them, we need to write some parsing code to interpret human-readable policy rules and convert them to `libcalico` Rule objects.

There might be some common function here between what the `calico-kubernetes` plugin does, and what `calicoctl` does.  However, I think that the two are logically separate enough that it makes sense to keep the parsing code separate (e.g the rules that the calico-kubernetes plugin interprets are not exactly the same as the calicoctl rules and may diverge further down the road).

**Comment by caseydavenport** [comment]
Fixed by #64
