### ISSUE TITLE
Calico dynamic routing vs static routes

### ISSUE THREAD

**Issue by Smana** [projectcalico/calico-kubernetes#42]
Hello,

I was wondering what are the drawbacks of using static routes instead of calico.
I mean i've discussed with my collegue of the network team : 
* we could provisonne several /24 subnets and configure static routes to a given number of nodes.
Let's say we'll never reach 20 nodes on a datacenter.
* we'll use the default docker networking.
This solution would be a bit simpler than dynamic routing.

Does it make sense ?
What are the advantages/drawbacks of using calico ?

Regards,
Smana

**Comment by lxpollitt** [comment]
If you are deploying at low scale then static route provisioning (rather than using BGP) can work fine.  You would obviously lose the ability to move a workload from one location to another one without changing it's IP.  (You might want to do this if for example you want to use Flocker to move database container from one location to another.)  

We've done demos of running Calico in static routing mode in the past, and could potentially work with you to get such support added natively into calicoctl.

The advantage of using Calico in such a scenario:
- Calico's policy engine can still be used to secure your containers.
- You avoid port mapping and NAT involved in Docker's "default" networking mode, which reduces deployment and operational complexity.  (Port mapping is generally considered to be painful once you get above small numbers of containers, and many people would say this is not as straightforward to manage as static or dynamic routing with Calico).
- You avoid needing on/off ramp style NAT if you are using Docker's "overlay" networking, which similarly reduces operational complexity.

If you don't care about any of those advantages, then using Docker's default network is a sensible enough thing to consider and we certainly wouldn't advocate you should use Calico if it gives you no advantages for your particular planned deployment and use cases.

Hope that makes sense.  Feel free to ask follow-up questions.

**Comment by Smana** [comment]
Ok, thank you i'll do benchmarks in order to compare the performances given the overhead caused by the port mapping of the default docker networking.
